#:import color_text inazuma.utility.kivy_markup_helper.color_text

<TaskText@MDLabel>:
    adaptive_height:True
    max_lines:0
    shorten:False
    markup:True
    font_style: "Label"
    role: "large"
    bold:True


<TaskCard>:
    adaptive_height:True
    radius:8
    padding:"20dp"
    md_bg_color:self.theme_cls.surfaceContainerHighColor

    TaskText:
        size_hint_x:.8
        text: root.media_item.title.english + f"; Episode {root.episode}"
    

